#ifndef __LIBFAT_PART_TYPE_H__
#define __LIBFAT_PART_TYPE_H__

typedef enum {
	PART_TYPE_EMPTY = 0x00,
	PART_TYPE_FAT12 = 0x01,
	PART_TYPE_FAT16_32 = 0x04,
	PART_TYPE_EXTENDED = 0x05,
	PART_TYPE_FAT16 = 0x06,
	PART_TYPE_NTFS = 0x07,
	PART_TYPE_FAT32 = 0x0B,
	PART_TYPE_FAT32_LBA = 0x0C,
	PART_TYPE_DYNAMIC = 0x42,
	PART_TYPE_LINUX_SWAP = 0x82,
	PART_TYPE_LINUX_LVM = 0x83
} part_type_t;

char *part_type_desc[] = {
	[PART_TYPE_EMPTY] = "Empty",
	[PART_TYPE_FAT12] = "FAT12",
	[PART_TYPE_FAT16_32] = "FAT16 <= 32MiB",
	[PART_TYPE_EXTENDED] = "Extended",
	[PART_TYPE_FAT16] = "FAT16",
	[PART_TYPE_NTFS] = "NTFS",
	[PART_TYPE_FAT32] = "FAT32",
	[PART_TYPE_FAT32_LBA] = "FAT32 LBA",
	[PART_TYPE_DYNAMIC] = "Dynamic",
	[PART_TYPE_LINUX_SWAP] = "Linux SWAP",
	[PART_TYPE_LINUX_LVM] = "Linux LVM"
};

#endif